Zerion SDK as Direct Dependency (#12)
Projects depending on this were getting the following error:

```
➜  near-safe-agent git:(main) ✗ bun test
bun test v1.1.38 (bf2f153f)

tests/safe.util.spec.ts:

# Unhandled error between tests
-------------------------------
error: Cannot find package 'zerion-sdk' from '/Users/bh2smith/Projects/bh2smith/near-safe-agent/node_modules/@bitteprotocol/agent-sdk/dist/evm/safe.js'
-------------------------------


 0 pass
 1 fail
 1 error
Ran 1 tests across 1 files. [236.00ms]
➜  near-safe-agent git:(main) ✗ npm ls zerion-sdk
near-safe-agent@0.1.0 /Users/bh2smith/Projects/bh2smith/near-safe-agent
└── (empty)
```

this is because zerion-sdk was not a dependency in the package but in
the project root.